### PR TITLE
[JENKINS-71789] Enable ${variable} support for email and cc fields

### PR DESCRIPTION
**Pull request by mikecirioli**
See [JENKINS-71789](https://issues.jenkins.io/browse/JENKINS-71789) for reproducer and details

Advisor had default support for escaping `${VAR}` expressions in the `email` configuration field, but otherwise did not support resolving variables for `email` or `cc` values, and would not correctly encode `${VAR}` as `{^${VAR}` if used as a CC value.

This PR enables encode/decode support for the email and cc values fields.

### Testing done

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by mikecirioli** [comment]
ping @aheritier for review please!

**Review by aheritier — DISMISSED** [review]
LGTM thanks @mikecirioli

**Comment by aheritier** [comment]
please use `mvn spotless:apply` to fix the formatting @mikecirioli

**Review by aheritier — APPROVED** [review]
All good. Thanks a lot !!!

**Review by Dohbedoh — APPROVED** [review]

**Review by PierreBtz — APPROVED** [review]
Lgtm thanks

**Pull request merged**
