### PR TITLE
[JARVIS-138] Add tests for excluded components

### PR DESCRIPTION
**Pull request by kwhetstone**
[JARVIS-138](https://cloudbees.atlassian.net/browse/JARVIS-138)

Added tests for the excluded components from the global configuration page.

@reviewbybees

### CODE REVIEW

**Comment by vilacides** [comment]
I can see tests for 25 elements which are the default ones selected, but I do not see a test for all o for a subset of the default ones and non default ones.

**Comment by Evildethow** [comment]
@kwhetstone can you follow up on the last comment?

**Comment by kwhetstone** [comment]
Line 140 is for the default components.  Line 151 is for all the components.  Line 153 is for none of the components.

**Comment by vilacides** [comment]
I see, that is why I couldn't see it here! Thanks @kwhetstone this and #14 LGTM 🐝

**Pull request merged**
