### PR TITLE
Name of the category for this management link

### PR DESCRIPTION
**Pull request by aheritier**
Requires Jenkins core 2.226+

Ref:
* https://jenkins.io/changelog/#v2.226
* https://github.com/jenkinsci/jenkins/pull/4546

### CODE REVIEW

**Comment by daniel-beck** [comment]
> Requires Jenkins core 2.226+

To clarify, it only does something on 2.226+. Older cores just ignore it.

Meanwhile, don't `@Override`.

**Comment by aheritier** [comment]
Result is:
 
Screenshot 2020-03-18 08 56 19

**Comment by oleg-nenashev** [comment]
According to the Javadoc in https://github.com/jenkinsci/jenkins/pull/4578, the selected category may need discussion. The category section says "while troubleshooting only matters when things go wrong" while this plugin is an advisory tool which might be useful when things are okay but could be improved

**Comment by aheritier** [comment]
@oleg-nenashev I agree cc @daniel-beck 
But Advisor can also highlight things which are going wrong and you don't see.
Not sure which other category could fit better otherwise (STATUS or a generic entry like CONFIGURATION or MISC ?)

**Comment by aheritier** [comment]
Based on others discussions with @MarkEWaite it seems that we agree in general to use the TROUBLESHOOTING category for Advisor. I will merge release the change later today. Thanks everyone

**Pull request merged**
